# Generated by Django 3.2.7 on 2021-10-04 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorize', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Tache'},
        ),
    ]
