# Generated by Django 3.2.7 on 2021-10-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorize', '0002_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, max_length=255, verbose_name='couleur'),
        ),
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=255, upload_to=''),
        ),
    ]
