# Generated by Django 3.2.7 on 2021-10-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorize', '0003_auto_20211004_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sous-titre'),
        ),
    ]
