# Generated by Django 3.2.7 on 2021-10-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorize', '0004_alter_task_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='checked',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
