# Generated by Django 3.2.7 on 2021-10-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorize', '0005_auto_20211004_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='titre')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='slug')),
            ],
        ),
    ]
