# Generated by Django 3.2.7 on 2021-10-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorize', '0007_alter_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Questionnaire sur Menus',
            },
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phoen',
            new_name='phone',
        ),
    ]
