# Generated by Django 3.2.7 on 2021-10-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorize', '0008_auto_20211005_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Catégorie'},
        ),
        migrations.AlterModelOptions(
            name='foodgame',
            options={'verbose_name': 'Questionnaire sur les Menu'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Statu'},
        ),
        migrations.AddField(
            model_name='foodgame',
            name='option',
            field=models.CharField(default='none', max_length=255, verbose_name='Différentes options'),
        ),
        migrations.AlterField(
            model_name='foodgame',
            name='answer',
            field=models.CharField(max_length=255, verbose_name='Réponse'),
        ),
        migrations.AlterField(
            model_name='foodgame',
            name='question',
            field=models.CharField(max_length=255, verbose_name='Question'),
        ),
    ]
