# Generated by Django 3.2.7 on 2021-10-06 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorize', '0009_auto_20211005_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='made_on',
            field=models.CharField(blank=True, default='none', max_length=255, verbose_name='date de réalisation'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='memorize.category', verbose_name='Catégories'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Nouvelle tâche'),
        ),
    ]
